name: web_bundle_split
description:  "A Flutter plugin for splitting web bundles."
version: 0.0.1
homepage: https://github.com/Jewel105/web_bundle_split/blob/main/README.md
repository: https://github.com/Jewel105/web_bundle_split
issue_tracker: https://github.com/Jewel105/web_bundle_split/issues

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  args: ^2.6.0
  path: ^1.9.0
  crypto: ^3.0.6

dev_dependencies:
  flutter_lints: ^4.0.0
